name: lab01
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: pip install nbconvert
      - run: |
          for file in $(find . -name "*.ipynb"); do
            echo "Converting $file"
            python -m nbconvert --to html "$file"
          done
