name: lab01
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: pip install nbconvert 
      - run: sudo apt-get install pandoc inkscape
      - uses: actions/checkout@v2
      - run: |
          for file in $(find lab* -type f -name "*.ipynb"); do
            python -m nbconvert --to pdf "$file"
          done
          done
