name: lab01
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: pip install nbconvert
      - uses: actions/checkout
      - run: |
          for file in $(find . -name "*.ipynb"); do
            python -m nbconvert "$file"
          done
